import {computed, defineComponent, h} from "vue";
import {stringProp} from "../../mixins/Commons";

export default defineComponent({
    name: "BsCardContent",
    props: {
        /**
         * Override html tag generated by `type` property.
         * @type {string|*}
         */
        tag: stringProp,
        /**
         * Card content variations, valid values are: `title`, `subtitle`, `text`.
         * @type {string|*}
         */
        type: {
            type: String,
            default: 'text',
            validator: (value: string): boolean => ['title', 'subtitle', 'text'].includes(value)
        },
    },
    setup(props, {slots}) {
        const tagName = computed((): string => {
            if (!props.tag) {
                return (props.type === 'title' ? 'h4' : props.type === 'subtitle' ? 'h5' : 'p');
            }
            return props.tag;
        });

        return () => h(
            tagName.value, {
                class: {
                    [`card-${props.type}`]: tagName.value,
                }
            }, [
                slots.default && slots.default()
            ]
        )
    }
});
